name: First WorkSpace
on: [push]

jobs:
  run-shell-basit:
    runs-on: ubuntu-latest
    steps:
     - name: print my name
       run: echo "my name is basit"
     - name: multiline script
       run: |
         pwd
         node -v 
         

     - name: checkout
       run: ls      
     - name: pyhton Command
       run: | 
         import platform
         print(platform.processor())
       shell: python
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: checkout_after
       run: ls     

       
